//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AAcheter : Cases
{
    protected int prixAchat;
    protected string nom_carte;
    protected int valHypothec;
    protected bool estPossedee;
    protected Joueur proprietaire;
    
    
    
	
    public AAcheter(string type,int prix, string nom,int valHyp) :base("AAcheter")
    {
        prixAchat = prix;
        valHypothec = valHyp;
        nom_carte = nom;
        estPossedee = false;
        proprietaire = null;
        
    }

}

