//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AAcheter : Cartes
{
    protected int prixAchat;
    protected string nom_carte;
    protected int valHypothec;
    protected bool estPossedee;
    protected Joueur proprietaire;
    protected Projet_Info_Monopoly.Groupe groupe;
	
    public AAcheter(Projet_Info_Monopoly.Groupe groupe,int prix, string nom)
    {
        prixAchat = prix;
        nom_carte = nom;
        estPossedee = false;
        proprietaire = null;
    }

}

