//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Cartes
    {
        protected int numeroCarte;
        protected string typeCarte;

        public Cartes(int num,string type)
        {
            numeroCarte = num;
            typeCarte = type;
        }
    }
}


