//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public abstract class Cases
    {
        public string nom_case { get; set; }
        

        public Cases(string _nom)
        {
            nom_case = _nom;
        }
<<<<<<< HEAD
=======

>>>>>>> 8a16a6a69149ce5e7c412f2576961ae5d71505ba
        public override string ToString()
        {
            string ch = "Vous tombez sur : " + nom_case;
            return ch;
        }
    }
}


