//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Compagnie : Propriete
    {

        public Compagnie(string nom_case,double prix,double prixL,double valHyp)
                : base(nom_case, prix, prixL, valHyp)
        {
            
        }

        public override double calculeLoyer(Joueur j)//Trouver un moyen d'avoir le résultat de dé de la personne tombant sur la case
        {
            
            int valDe = j.lanceDe();//ne va pas puisqu'il relance les dés, ce qu'on ne veut pas .. 
            int nombreCompagnie = j.calculeNombreCompagnies();
            if(nombreCompagnie==1)
            {
                Console.WriteLine("Val de" + valDe);
                prixLoyer = valDe * 4;
                   
            }
            else if(nombreCompagnie==2)
            {
                prixLoyer = valDe * 10;
                
            }
            return prixLoyer;

        }

        public void affiche_info_compagnie()
        {
            
                Console.Clear();
                Console.WriteLine("Nom : " + nom_case + "\nPrix : " + prixAchat );

            


        }
    }
}


