//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Compagnie : Propriete
    {

        public Compagnie(string nom_case,double prix,double prixL,double valHyp)
                : base(nom_case, prix, prixL, valHyp)
        {
            
        }

        public double calculeLoyer(int nombreCompagnie,int valDe)
        {
            double loyer = 0;
            if(nombreCompagnie==1)
            {
                loyer = valDe * 4;
                
            }
            else if(nombreCompagnie==2)
            {
                loyer = valDe * 10;
                
            }
            return loyer;

        }

        public void affiche_info_compagnie()
        {
            ConsoleKeyInfo c;

            Console.WriteLine("\nVoulez-vous voir les caractéristiques de cette carte ? (o/n)");
            do
            {

                c = Console.ReadKey();
            }
            while (c.KeyChar != 'o' && c.KeyChar != 'n');
            if (c.KeyChar == 'o')
            {
                Console.Clear();
                Console.WriteLine("Nom : " + nom_case + "\nPrix : " + prixAchat );

            }


        }
    }
}


