//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Compagnie : Propriete
    {

        public Compagnie(string nom,double prix,double prixL,double valHyp)
                : base(nom, prix, prixL, valHyp)
        {
            
        }

        public double calculLoyer(int nombreCompagnie,int valDe)
        {
            double loyer = 0;
            if(nombreCompagnie==1)
            {
                loyer = valDe * 4;
                
            }
            else if(nombreCompagnie==2)
            {
                loyer = valDe * 10;
                
            }
            return loyer;

        }
    }
}


