//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Gare : Propriete
    {
        

        public Gare(string nom, double prix, double prixL,double valHyp):base(nom,prix,prixL,valHyp)       
        {

        }

        public double calculLoyer(int nombreGares)
        {
            double loyer = 25 * nombreGares;
            return loyer;
        }


    }

}

