//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Joueur : Plateau
{
	public virtual string nom_joueur
	{
		get;
		set;
	}

	public virtual int numero_joueur
	{
		get;
		set;
	}

	public virtual int argent
	{
		get;
		set;
	}

	public virtual int position
	{
		get;
		set;
	}
    public Joueur(string nom, int numero, int arg, int pos)
    {
        nom_joueur = nom;
        numero_joueur = numero;
        argent = arg;
        position = pos; 
    }

}

