//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Joueur
    {
        private string nom_joueur { get; set; }
        private double argent { get; set; } // argent du joueur (initialisé à 1500)
        private int position { get; set; } // la position du joueur sur le plateau
        public bool estEnPrison { get; set; }
        public bool estMort { get; set; }
        private LinkedList<Cartes> cartesDuJoueur; // 
        public LinkedList<Propriete> proprieteDuJoueur;
        private static Random r = new Random();



        public Joueur(string nom)
        {
            nom_joueur = nom;
            argent = 1500;
            position = 0;
            cartesDuJoueur = new LinkedList<Cartes>(); // on initialise une liste de cartes dans laquelle on va ajouter les cartes qu'il possède
            proprieteDuJoueur = new LinkedList<Propriete>();
            estEnPrison = false;
        }

        public void acheterPropriete(Propriete p)
        {
            if ((this.argent > p.prixAchat) && p.estPossedee == false)
            {
                ConsoleKeyInfo c;
                Console.WriteLine("Souhaitez vous acheter {0} pour {1} euros ? (o) (n)", p.nom_prop, p.prixAchat);
                do
                {
                    c = Console.ReadKey();
                }
                while (c.KeyChar != 'o' && c.KeyChar != 'n');
                if (c.KeyChar == 'y')
                {
                    Console.WriteLine("Vous avez acheté {0}", p.nom_prop);
                    p.proprietaire = this;
                    p.estPossedee = true;
                    this.proprieteDuJoueur.AddLast(p);
                    this.argent -= p.prixAchat;
                    //this.addCard(carte qui correspond à la propriete)
                }

            }
            else if (this.argent < p.prixAchat)
            {
                Console.WriteLine("Vous n'avez pas assez d'argent pour acheter cette propriété");
            }

        }

        public int avancer()
        {
            position += lanceDe();
            if(position>=40)
            {
                position = position % 40;
                argent += 200; // pouvoir définir une valeur modifiable depuis le XML
            }
            return position;


        }

        public int lanceDe()
        {
            int compteurDouble = 0;
            int de1 = r.Next(1, 7);
            int de2 = r.Next(1, 7);
            int total = de1 + de2;

            if (de1 == de2)
            {
                Console.WriteLine("Double " + de1 + " ! ");
                compteurDouble++;
            }
            else
            {
                Console.WriteLine("Vous avez fait : " + total + " (" + de1 + "+" + de2 + ")");
            }

            return total;
        }

        public void addCard(Cartes c)
        {
            cartesDuJoueur.AddLast(c);

        }
        public void removeCard(Cartes c)
        {
            
        }

    }
}


