//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Joueur 
{
    private string nom_joueur;
    private int argent;
    private Cases position;

    public Joueur(string nom)
    {
        nom_joueur = nom;
        argent = 1500;
        

    }

}

