//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Propriete : AAcheter
    {
        protected double prixMaison;
        protected double prixHotel;
        protected int nbMaisonConstruites;
        protected int nbHotelConstruits;
        public enum couleur { bleu,cyan, rose, marron,orange,rouge,jaune,vert};
        public couleur Couleur { get; set; }

        public Propriete(double prixM, double prixH, string nom, double prix, double prixL, double valHyp, couleur c):base(nom,prix,prixL,valHyp)
        {
            prixMaison = prixM;
            prixHotel = prixH;
            nbMaisonConstruites = 0;
            nbHotelConstruits = 0;

        }


        public bool peutConstruireHotel(Joueur j)
        {
            if (nbMaisonConstruites == 4)
            { return true; }
            return false;
        }

        public void calculLoyer()
        {
            
        }

    }
}


