//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Propriete : AAcheter
{
	public virtual int prixMaison
	{
		get;
		set;
	}

	public virtual int prixHotel
	{
		get;
		set;
	}

	public virtual string couleur
	{
		get;
		set;
	}

}

