//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Propriete : AAcheter
{
    private int loyerTerrainNu;
    private int loyer1Maison;
    private int loyer2Maison;
    private int loyer3Maison;
    private int loyer4Maison;
    private int loyerHotel;
    private int nbMaison;
	public virtual string couleur
	{
		get;
		set;
	}

    public Propriete (int prixAchat,int unPrix,string uneCouleur, int m1, int m2, int m3, int m4, int h, int valHypo)
    {
        loyerTerrainNu = unPrix;
        loyer1Maison = m1;
        loyer2Maison = m2;
        loyer3Maison = m3;
        loyer4Maison = m4;
        loyerHotel = h;
        valHypo = unPrix / 2;
        couleur = uneCouleur;
            
    }

    public string getCouleur()
    {
        return this.couleur;
    }

    public bool peutConstruireHotel(Joueur j)
    {
        if(nbMaison==4)
        { return true; }
        return false;
    }

}

