//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Projet_Info_Monopoly
{
    public class Transaction : Cartes
    {
        public double valeur;

        public Transaction(typeCarte type, string nom, double value):base(type,nom)
        {
            valeur = value;
        }

        public override void EffetCarte(Joueur j)
        {
            
            j.argent += valeur;
            base.EffetCarte(j);
            Console.WriteLine("Vous avez desormais" + j.argent);
        }

       
        
    }
}

